// <auto-generated />
using System;
using FinalProject_Jenotan.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject_Jenotan.Migrations
{
    [DbContext(typeof(TinyCollegeDbContextSQLServer))]
    [Migration("20260427093205_updatev4")]
    partial class updatev4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Building", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Class", b =>
                {
                    b.Property<string>("ClassId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ClassCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<TimeOnly>("ClassTime")
                        .HasColumnType("time");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsOnGoing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("RoomCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClassId");

                    b.HasIndex("CourseId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("RoomCode");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ClassCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DepartmentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Enrollment", b =>
                {
                    b.Property<string>("EnrollmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<float?>("Grade")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Faculty", b =>
                {
                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ClassCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacultyId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Major", b =>
                {
                    b.Property<string>("MajorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MajorId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Room", b =>
                {
                    b.Property<string>("RoomCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoomCode");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.School", b =>
                {
                    b.Property<string>("SchooldId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchooldId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsEnrolled")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MajorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("MajorId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Inventory", b =>
                {
                    b.Property<string>("InventoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MechanicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InventoryId");

                    b.HasIndex("MechanicId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.MaintenanceDetails", b =>
                {
                    b.Property<string>("MDetailsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("datetime2");

                    b.Property<string>("MLogId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaintenancePerformed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MechanicId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MDetailsId");

                    b.HasIndex("MLogId");

                    b.HasIndex("MechanicId");

                    b.ToTable("MaintenanceDetails");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.MaintenanceLog", b =>
                {
                    b.Property<string>("MLogId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MLogId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("VehicleId1");

                    b.ToTable("MaintenanceLogs");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Mechanic", b =>
                {
                    b.Property<string>("MechanicId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAuthorizedToSign")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MechanicId");

                    b.ToTable("Mechanics");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Parts", b =>
                {
                    b.Property<string>("PartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InvenotryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("PartId");

                    b.HasIndex("InvenotryId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.PartsUsageReport", b =>
                {
                    b.Property<string>("PURId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalPartsUsed")
                        .HasColumnType("int");

                    b.HasKey("PURId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId1");

                    b.ToTable("PartsUsageReports");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.PartsUsedForm", b =>
                {
                    b.Property<string>("PUFormId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MDetailsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MLogId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MechanicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PURId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QtyUsed")
                        .HasColumnType("int");

                    b.HasKey("PUFormId");

                    b.HasIndex("MDetailsId");

                    b.HasIndex("MLogId");

                    b.HasIndex("MechanicId");

                    b.HasIndex("PURId");

                    b.HasIndex("PartsId");

                    b.ToTable("PartsUsedForms");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.VehicleReleaseForm", b =>
                {
                    b.Property<string>("VRFormId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateSigned")
                        .HasColumnType("datetime2");

                    b.Property<string>("MLogId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MechanicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VRFormId");

                    b.HasIndex("MLogId")
                        .IsUnique();

                    b.HasIndex("MechanicId");

                    b.ToTable("VehicleReleaseForms");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.CheckoutForm", b =>
                {
                    b.Property<string>("CheckoutId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCheckedOut")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnGoing")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("RFormId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CheckoutId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("RFormId");

                    b.ToTable("CheckoutForms");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.CompletionForm", b =>
                {
                    b.Property<string>("CFormId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CheckoutFormLinkCheckoutId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CheckoutId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCardNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("EndOdo")
                        .HasColumnType("real");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FacultyId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("FuelCost")
                        .HasColumnType("real");

                    b.Property<float>("StartOdo")
                        .HasColumnType("real");

                    b.Property<float>("TripCost")
                        .HasColumnType("real");

                    b.Property<string>("VReportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CFormId");

                    b.HasIndex("CheckoutFormLinkCheckoutId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("FacultyId1");

                    b.HasIndex("VReportId");

                    b.HasIndex("VehicleId");

                    b.ToTable("CompletionForms");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.ReservationForm", b =>
                {
                    b.Property<string>("RFormId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FacultyId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ISApproved")
                        .HasColumnType("bit");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RFormId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("FacultyId1");

                    b.HasIndex("VehicleId");

                    b.ToTable("ReservationForms");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Vehicle", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CostPerMilage")
                        .HasColumnType("real");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Mileage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("OdoReading")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.VehicleReport", b =>
                {
                    b.Property<string>("VReportId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeLinkEmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TimesUsed")
                        .HasColumnType("int");

                    b.Property<float>("TotalMileageGained")
                        .HasColumnType("real");

                    b.Property<string>("VehicleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("VReportId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeLinkEmployeeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleReports");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Class", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Course", "CourseLink")
                        .WithMany("ClassList")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Faculty", "FacultyLink")
                        .WithMany("ClassTeachingList")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Room", "RoomLink")
                        .WithMany("ClassList")
                        .HasForeignKey("RoomCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CourseLink");

                    b.Navigation("FacultyLink");

                    b.Navigation("RoomLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Course", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Department", "DepartmentLink")
                        .WithMany("CourseList")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Department", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Faculty", "FacultyLink")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.School", "SchoolLink")
                        .WithMany("DepartmentList")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacultyLink");

                    b.Navigation("SchoolLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Enrollment", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Class", "ClassLink")
                        .WithMany("EnrollmentList")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Student", "StudentLink")
                        .WithMany("EnrollmentList")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassLink");

                    b.Navigation("StudentLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Faculty", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Department", "DepartmentLink")
                        .WithMany("FacultyList")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DepartmentLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Major", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Department", "DepartmentLink")
                        .WithMany("MajorList")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Room", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Building", "BuildingLink")
                        .WithMany("RoomList")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.School", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Faculty", "FacultyLink")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FacultyLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Student", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Faculty", "FacultyLink")
                        .WithMany("StudentAdviseList")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Major", "MajorLink")
                        .WithMany("StudentList")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FacultyLink");

                    b.Navigation("MajorLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Inventory", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Mechanic", "MechanicLink")
                        .WithMany("InventoryList")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MechanicLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.MaintenanceDetails", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.MaintenanceLog", "MaintenanceLogLink")
                        .WithMany("MaintenanceDetailsList")
                        .HasForeignKey("MLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Mechanic", "MechanicLink")
                        .WithMany("MaintenanceDetailList")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MaintenanceLogLink");

                    b.Navigation("MechanicLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.MaintenanceLog", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Vehicle", "VehicleLink")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Vehicle", null)
                        .WithMany("MaintenanceLogList")
                        .HasForeignKey("VehicleId1");

                    b.Navigation("VehicleLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Parts", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Inventory", "InventoryLink")
                        .WithMany("PartsList")
                        .HasForeignKey("InvenotryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.PartsUsageReport", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Employee", "EmployeeLink")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Employee", null)
                        .WithMany("PartsUsageReportList")
                        .HasForeignKey("EmployeeId1");

                    b.Navigation("EmployeeLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.PartsUsedForm", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.MaintenanceDetails", null)
                        .WithMany("PartsUsedFormList")
                        .HasForeignKey("MDetailsId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.MaintenanceLog", "MaintenanceLogLink")
                        .WithMany("PartsUsedFormList")
                        .HasForeignKey("MLogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Mechanic", "MechanicLink")
                        .WithMany("PartUsedFormList")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.PartsUsageReport", "PartsUsageReportLink")
                        .WithMany("PartsUsedFormList")
                        .HasForeignKey("PURId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Parts", "PartsLink")
                        .WithMany("PartsUsedFormList")
                        .HasForeignKey("PartsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaintenanceLogLink");

                    b.Navigation("MechanicLink");

                    b.Navigation("PartsLink");

                    b.Navigation("PartsUsageReportLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.VehicleReleaseForm", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.MaintenanceLog", "MaintenanceLogLink")
                        .WithMany("VehicleReleaseFormList")
                        .HasForeignKey("MLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Mechanic", "MechanicLink")
                        .WithMany("VehicleReleaseFormList")
                        .HasForeignKey("MechanicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaintenanceLogLink");

                    b.Navigation("MechanicLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.CheckoutForm", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Employee", "EmployeeLink")
                        .WithMany("CheckoutFormList")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Faculty", "FacultyLink")
                        .WithMany("CheckoutFormList")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.ReservationForm", "ReservationFormLink")
                        .WithMany("CheckoutFormList")
                        .HasForeignKey("RFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeLink");

                    b.Navigation("FacultyLink");

                    b.Navigation("ReservationFormLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.CompletionForm", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.CheckoutForm", "CheckoutFormLink")
                        .WithMany("CompletionForms")
                        .HasForeignKey("CheckoutFormLinkCheckoutId");

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Employee", "EmployeeLink")
                        .WithMany("CompletionFormList")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Faculty", "FacultyLink")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Faculty", null)
                        .WithMany("CompletionFormList")
                        .HasForeignKey("FacultyId1");

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.VehicleReport", "VehicleReportLink")
                        .WithMany("CompletionFormList")
                        .HasForeignKey("VReportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Vehicle", "VehicleLink")
                        .WithMany("CompletionFormList")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckoutFormLink");

                    b.Navigation("EmployeeLink");

                    b.Navigation("FacultyLink");

                    b.Navigation("VehicleLink");

                    b.Navigation("VehicleReportLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.ReservationForm", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Employee", "EmployeeLink")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Faculty", "FacultyLink")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Faculty", null)
                        .WithMany("ReservationFormList")
                        .HasForeignKey("FacultyId1");

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Vehicle", "VehicleLink")
                        .WithMany("ReservationFormList")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeLink");

                    b.Navigation("FacultyLink");

                    b.Navigation("VehicleLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.VehicleReport", b =>
                {
                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Employee", null)
                        .WithMany("VehicleReportList")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Employee", "EmployeeLink")
                        .WithMany()
                        .HasForeignKey("EmployeeLinkEmployeeId");

                    b.HasOne("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Vehicle", "VehicleLink")
                        .WithMany("VehicleReportList")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EmployeeLink");

                    b.Navigation("VehicleLink");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Building", b =>
                {
                    b.Navigation("RoomList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Class", b =>
                {
                    b.Navigation("EnrollmentList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Course", b =>
                {
                    b.Navigation("ClassList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Department", b =>
                {
                    b.Navigation("CourseList");

                    b.Navigation("FacultyList");

                    b.Navigation("MajorList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Faculty", b =>
                {
                    b.Navigation("CheckoutFormList");

                    b.Navigation("ClassTeachingList");

                    b.Navigation("CompletionFormList");

                    b.Navigation("ReservationFormList");

                    b.Navigation("StudentAdviseList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Major", b =>
                {
                    b.Navigation("StudentList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Room", b =>
                {
                    b.Navigation("ClassList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.School", b =>
                {
                    b.Navigation("DepartmentList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.EnrollmentSystem.Student", b =>
                {
                    b.Navigation("EnrollmentList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Inventory", b =>
                {
                    b.Navigation("PartsList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.MaintenanceDetails", b =>
                {
                    b.Navigation("PartsUsedFormList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.MaintenanceLog", b =>
                {
                    b.Navigation("MaintenanceDetailsList");

                    b.Navigation("PartsUsedFormList");

                    b.Navigation("VehicleReleaseFormList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Mechanic", b =>
                {
                    b.Navigation("InventoryList");

                    b.Navigation("MaintenanceDetailList");

                    b.Navigation("PartUsedFormList");

                    b.Navigation("VehicleReleaseFormList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.Parts", b =>
                {
                    b.Navigation("PartsUsedFormList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Maintenance.PartsUsageReport", b =>
                {
                    b.Navigation("PartsUsedFormList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.CheckoutForm", b =>
                {
                    b.Navigation("CompletionForms");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Employee", b =>
                {
                    b.Navigation("CheckoutFormList");

                    b.Navigation("CompletionFormList");

                    b.Navigation("PartsUsageReportList");

                    b.Navigation("VehicleReportList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.ReservationForm", b =>
                {
                    b.Navigation("CheckoutFormList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.Vehicle", b =>
                {
                    b.Navigation("CompletionFormList");

                    b.Navigation("MaintenanceLogList");

                    b.Navigation("ReservationFormList");

                    b.Navigation("VehicleReportList");
                });

            modelBuilder.Entity("FinalProject_Jenotan.Database.Models.MotorPoolSystem.Reservation.VehicleReport", b =>
                {
                    b.Navigation("CompletionFormList");
                });
#pragma warning restore 612, 618
        }
    }
}
